### PR TITLE
Added 'key' field in AppTemplateValuesSourceRef

### LINKED ISSUE #784: Support secret key in AppTemplateValuesSourceRef
**Describe the problem/challenge you have**
We want to use a shared Secret across Package CRs, and use different keys in the Secret for different Package CRs.

**Describe the solution you'd like**
Add 'key' field in AppTemplateValuesSourceRef just like AppClusterKubeconfigSecretRef
https://github.com/vmware-tanzu/carvel-kapp-controller/blob/7d7ea1d65be1034906aca0145b895627ed4e233c/pkg/apis/kappctrl/v1alpha1/types.go#L92-L99

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by jignyasamishra**
#### What this PR does / why we need it:
Introduced a new optional field `key` of type `string`. This key can be used to reference specific instances of `AppTemplateValuesSourceRef` in templates or configurations.
#### Which issue(s) this PR fixes:

Fixes #784

#### Does this PR introduce a user-facing change?

```release-note

```

##### Review Checklist:

- [x] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [ ] Relevant tests are added or updated
- [ ] Relevant docs in this repo added or updated
- [ ] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [x] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by praveenrewar — COMMENTED** [review]
@jignyasamishra Thank you for looking into this issue. Are you still working on this? We would also need some logic to handle the value of that `Key` in `AppTemplateValuesSourceRef`. Also, the tests will have to be updated accordingly. 
(There are some scripts in the hack directory that you can use to build and deploy kapp-controller, and run unit and integration tests. Please refer to docs directory for more details)

**Comment by jignyasamishra** [comment]
> @jignyasamishra Thank you for looking into this issue. Are you still working on this? We would also need some logic to handle the value of that `Key` in `AppTemplateValuesSourceRef`. Also, the tests will have to be updated accordingly. (There are some scripts in the hack directory that you can use to build and deploy kapp-controller, and run unit and integration tests. Please refer to docs directory for more details)

Thank you so much for your feedback!! Yes i am working on it.

**Comment by jignyasamishra** [comment]
Hello @praveenrewar I have addressed the changes and also changed the unit tests, the unit-tests are passing.Please have a look, thank you!

**Review by praveenrewar — COMMENTED** [review]
@jignyasamishra You have made the changes in the cli's vendor directory. Could you make those in the root. Also, once you make those changes, please run the scripts in the hack directory (namely, gen.sh, gen-apiserver.sh and gen-crds.sh).

**Comment by renuy** [comment]
@jignyasamishra ,
Please check the tests. Once they are fixed, we will prioritize the review

**Comment by hoegaarden** [comment]
Somewhat late to the game here, but some of my thoughts -- just spit-balling:

Would it be useful to make this new option a list, `keys`?  

I know I could add values from multiple keys by using multiple `valuesFrom` with the same secret[^1], e.g.:
  ```
  valuesFrom:
  - secretRef:
      name: my-secret
      key: some-key
  - secretRef:
      name: my-secret
      key: some-other-key
  ```
  while this is what I am thinking about:
  ```
  valuesFrom:
  - secretRef:
      name: my-secret
      keys:
      - some-key
      - some-other-key
  ```
[^1]: same goes for config maps, as `AppTemplateValuesSourceRef` is shared across those two


I know the [related issue](https://github.com/carvel-dev/kapp-controller/issues/784) references [prior art for picking up a secret holding a kube config](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/7d7ea1d65be1034906aca0145b895627ed4e233c/pkg/apis/kappctrl/v1alpha1/types.go#L92-L99), however I think these two concerns are slightly different: The kubeconfig part explicitly pulls out just one item of the secret (by default `value`, we don't merge multiple items here, we only ever want to reference one), where using a secret as data-values, we generally want to get multiple, by default all, items.

**Comment by praveenrewar** [comment]
@hoegaarden I think it makes sense to make keys a list. Thank you so much for the suggestion 😄 
@jignyasamishra Are you still working on this? Let me know if you need some help or even if you are not able to continue working on this at the moment.

**Comment by jignyasamishra** [comment]
> @hoegaarden I think it makes sense to make keys a list. Thank you so much for the suggestion 😄 @jignyasamishra Are you still working on this? Let me know if you need some help or even if you are not able to continue working on this at the moment.

sorry for the late reply @praveenrewar  , I am occupied with my other work hence wont be able to work on this issue. Thank you and sorry for the inconvenience

**Comment by praveenrewar** [comment]
No worries @jignyasamishra! I am closing this PR for now but feel free to reopen it if you want to get back to it.

**Pull request closed without merging**
