### PR TITLE
Add kctrl binaries to release artifacts

### PR DESCRIPTION
**Pull request by praveenrewar**
Update release process to add kctrl binaries as release artefacts

```release-note
NONE
```

### CODE REVIEW

**Review by joe-kimmel-vmw — APPROVED** [review]

**Review by neil-hickey — APPROVED** [review]
LGTM

**Comment by neil-hickey** [comment]
hey @praveenrewar is this good to be merged? Is kctrl is ready to be published on the next release? I think the next release is aimed at next week

**Comment by rohitagg2020** [comment]
LGTM

**Comment by praveenrewar** [comment]
Hi @neil-hickey. Yep, this is good to be merged as we are planning to release kctrl this week.

**Pull request merged**
