### PR TITLE
Fixing the test case TestConfig_TrustCACerts ( ssl on is removed)

### PR DESCRIPTION
**Pull request by rohitagg2020**
#### What this PR does / why we need it:
Removed `ssl on` from nginx.conf as this configuration is not supported anymore by nginx.
Replaced it with `listen 443 ssl`
#### Which issue(s) this PR fixes:
Fixing the test case TestConfig_TrustCACerts
Fixes #

#### Does this PR introduce a user-facing change?
None

##### Review Checklist:

- [ ] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [ ] Relevant tests are added or updated
- [ ] Relevant docs in this repo added or updated
- [ ] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [ ] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by praveenrewar — APPROVED** [review]
LGTM!

**Comment by praveenrewar** [comment]
Can we also cherry pick this to the other lts branches?

**Comment by rohitagg2020** [comment]
> Can we also cherry pick this to the other lts branches?

Will do it once it is merged

**Pull request merged**
