### PR TITLE
Adds ability to force HTTP Basic when fetching from git repos

### LINKED ISSUE #1485: Support forcing basic authentication for fetches that use git
**Describe the problem/challenge you have**
See: https://github.com/carvel-dev/vendir/issues/361 for upstream `vendir` issue.

This is the downstream issue that is necessary to bubble up this feature to the kapp-controller app CR.

**Describe the solution you'd like**
```
    - git:
        forceHTTPBasicAuth: true # Adding this configuration option.
        secretRef:
          name: secret-name # Same formatted secret, unchanged, includes username and password.
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by joaopapereira**
#### What this PR does / why we need it:
Enable the vendir ability to force HTTP Basic when fetching from a git repository.

#### Which issue(s) this PR fixes:

Fixes #1485 

#### Does this PR introduce a user-facing change?
```release-note
Allow users to define forceHTTPBasicAuth in the fetch phase.
```

##### Review Checklist:

- [ ] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [ ] Relevant tests are added or updated
- [ ] Relevant docs in this repo added or updated
- [ ] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [ ] Code is at least as readable and maintainable as it was before this
  change

### CODE REVIEW

**Review by praveenrewar — COMMENTED** [review]
Changes looks good to me, I am not sure why the tests are timing out in a kind cluster and that too after 6 hours even though we have a timeout of 60m. 
One thing I noticed it that we have missed updating golang version in the kind action (cc @sethiyash)
Also, could we try to show the test logs instead of pushing them to a file and see where the timeout is happening?

**Comment by sethiyash** [comment]
Ah! Missed it somehow, Raised [this](https://github.com/carvel-dev/kapp-controller/pull/1496) separate PR for bumping go version in kind GH action. 
cc: @praveenrewar

**Comment by joaopapereira** [comment]
I just rebased with develop branch let us see if it goes through 😄

**Review by praveenrewar — APPROVED** [review]
LGTM!

**Pull request merged**
